---
layout: default
---

Text can be **bold**, _italic_, or ~~strikethrough~~.

[Link to another page](another-page).

There should be whitespace between paragraphs.

There should be whitespace between paragraphs. We recommend including a README, or a file with information about your project.

# [](#header-1)Header 1

This is a normal paragraph following a header. GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects from anywhere.

## [](#header-2)Header 2

> This is a blockquote following a header.
>
> When something is important enough, you do it even if the odds are not in your favor.

### [](#header-3)Header 3

```js
// Javascript code with syntax highlighting.
var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l)
  return true;
}
```

```ruby
# Ruby code with syntax highlighting
GitHubPages::Dependencies.gems.each do |gem, version|
  s.add_dependency(gem, "= #{version}")
end
```

#### [](#header-4)Header 4

*   This is an unordered list following a header.
*   This is an unordered list following a header.
*   This is an unordered list following a header.

##### [](#header-5)Header 5

1.  This is an ordered list following a header.
2.  This is an ordered list following a header.
3.  This is an ordered list following a header.

###### [](#header-6)Header 6

| head1        | head two          | three |
|:-------------|:------------------|:------|
| ok           | good swedish fish | nice  |
| out of stock | good and plenty   | nice  |
| ok           | good `oreos`      | hmm   |
| ok           | good `zoute` drop | yumm  |

### There's a horizontal rule below this.

* * *

### Here is an unordered list:

*   Item foo
*   Item bar
*   Item baz
*   Item zip

### And an ordered list:

1.  Item one
1.  Item two
1.  Item three
1.  Item four

### And a nested list:

- level 1 item
  - level 2 item
  - level 2 item
    - level 3 item
    - level 3 item
- level 1 item
  - level 2 item
  - level 2 item
  - level 2 item
- level 1 item
  - level 2 item
  - level 2 item
- level 1 item

### Small image

![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

### Large image

![](https://guides.github.com/activities/hello-world/branching.png)


### Definition lists can be used with HTML syntax.

<dl>
<dt>Name</dt>
<dd>Godzilla</dd>
<dt>Born</dt>
<dd>1952</dd>
<dt>Birthplace</dt>
<dd>Japan</dd>
<dt>Color</dt>
<dd>Green</dd>
</dl>

```
Long, single-line code blocks should not wrap. They should horizontally scroll if they are too long. This line should be long enough to demonstrate this.
```

```
The final element.
```
# Following scripts failed 
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    [FATAL] Module python-libsbml is not found.
    This module can be installed by following command in terminal:
    	 easy_install python-libsbml
    Traceback (most recent call last):
      File "loadSbmlmodel.py", line 122, in <module>
        modelPath, modelpathexist,msg = main()
      File "loadSbmlmodel.py", line 84, in main
        elif sbmlId.path != '/':
    AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../traub_2005/py/display_morphology.py

```
  Traceback (most recent call last):
    File "display_morphology.py", line 52, in <module>
      import networkx as nx
  ImportError: No module named networkx
```
# Following scripts failed 
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    [FATAL] Module python-libsbml is not found.
    This module can be installed by following command in terminal:
    	 easy_install python-libsbml
    Traceback (most recent call last):
      File "loadSbmlmodel.py", line 122, in <module>
        modelPath, modelpathexist,msg = main()
      File "loadSbmlmodel.py", line 84, in main
        elif sbmlId.path != '/':
    AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../traub_2005/py/display_morphology.py

```
  Traceback (most recent call last):
    File "display_morphology.py", line 52, in <module>
      import networkx as nx
  ImportError: No module named networkx
```
# Following scripts failed 
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    [FATAL] Module python-libsbml is not found.
    This module can be installed by following command in terminal:
    	 easy_install python-libsbml
    Traceback (most recent call last):
      File "loadSbmlmodel.py", line 122, in <module>
        modelPath, modelpathexist,msg = main()
      File "loadSbmlmodel.py", line 84, in main
        elif sbmlId.path != '/':
    AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../traub_2005/py/display_morphology.py

```
  Traceback (most recent call last):
    File "display_morphology.py", line 52, in <module>
      import networkx as nx
  ImportError: No module named networkx
```
# Following scripts failed 
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    [FATAL] Module python-libsbml is not found.
    This module can be installed by following command in terminal:
    	 easy_install python-libsbml
    Traceback (most recent call last):
      File "loadSbmlmodel.py", line 122, in <module>
        modelPath, modelpathexist,msg = main()
      File "loadSbmlmodel.py", line 84, in main
        elif sbmlId.path != '/':
    AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../traub_2005/py/display_morphology.py

```
  Traceback (most recent call last):
    File "display_morphology.py", line 52, in <module>
      import networkx as nx
  ImportError: No module named networkx
```
# Following scripts failed 
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    [FATAL] Module python-libsbml is not found.
    This module can be installed by following command in terminal:
    	 easy_install python-libsbml
    Traceback (most recent call last):
      File "loadSbmlmodel.py", line 122, in <module>
        modelPath, modelpathexist,msg = main()
      File "loadSbmlmodel.py", line 84, in main
        elif sbmlId.path != '/':
    AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../traub_2005/py/display_morphology.py

```
  Traceback (most recent call last):
    File "display_morphology.py", line 52, in <module>
      import networkx as nx
  ImportError: No module named networkx
```
# Following scripts failed 
# Following scripts failed 
- [ ] ./../neuroml/LIF/LIFxml_firing.py

```
  moose.nml.neuroml: INFO     Loading neuroml file cells_channels/LIF.morph.xml 
  INFO:moose.nml.neuroml:Loading neuroml file cells_channels/LIF.morph.xml 
  moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
  INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
  INFO:root:Loading cell LIF into /library .
  INFO:root:readMorphML using combineSegments = False
  INFO:root:Loading mechanism IaF into library.
  TypeError: must be real number, not str
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last)INFO:root:Loading mechanism Gran_H_98 into library.
  INFO:root:Loading mechanism Gran_CaHVA_98 into library.
  INFO:root:Loading mechanism Gran_KCa_98 into library.
  _channels/LIF.morph.xml')
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NeuroML.py", line 139, in readNeuroMLFromFile
      cellDict = mmlR.readMorphML(cell,params=params,lengthUnits=self.lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/LIF/twoLIFxml_firing.py

```
  moose.nml.neuroml: INFO     Loading neuroml file allChannelsCell.net.xml 
  INFO:moose.nml.neuroml:Loading neuroml file allChannelsCell.net.xml 
  moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
  INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
  INFO:root:Reading morphology from /home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism Kd_STG into library.
  mbineSegments = False
  INFO:root:Loading mechanism IaF into library.
  TypeError: must be real number, not str
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "twoLIFxml_firing.py", line 47, in <module>
      populationDict,projectionDict = create_twoLIFs()
    File "twoLIFxml_firing.py", line 35, in create_twoLIFs
      NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
      return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
      self.network.findall(".//{"+nml_ns+"}population")
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
      [ self.createPopulation(pop) for pop in
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
      cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
      cellDict = self.readMorphML(cell,params,lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/lobster_pyloric/channels/ChannelTest.py

```
    moose.nml.neuroml: INFO     Loading neuroml file allChannelsCell.net.xml 
    INFO:moose.nml.neuroml:Loading neuroml file allChannelsCell.net.xml 
    moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
    INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
    INFO:root:Reading morphology from /home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism Kd_STG into library.
    mbineSegments = False
    INFO:root:Loading mechanism IaF into library.
    TypeError: must be real number, not str
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "twoLIFxml_firing.py", line 47, in <module>
        populationDict,projectionDict = create_twoLIFs()
      File "twoLIFxml_firing.py", line 35, in create_twoLIFs
        NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
        return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
        self.network.findall(".//{"+nml_ns+"}population")
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
        [ self.createPopulation(pop) for pop in
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
        cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
        cellDict = self.readMorphML(cell,params,lengthUnits)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
        moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
    SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../parallelSolver/Fig2_v4.py

```
  tau = 0.004 lambda = 0.00031622776601683794
  0
  -----------------
  4.96729413289805e-10 4.96729413289805e-10 0.0 0.0 0.0 0.0 0.0 0.0 
  0.0 0.0 0.0 0.0 0.0 0.0 4.967Warning: Moogli not found. All moogli calls will use dummy functions
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0)) 
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( 0.1 + -5.0*x1 + 5.0*x1*x1 + -1.0*x1*x1*x1 + 10.0*x0*x1/(1+x1+10*x2) + -5.0*x1*x2) 
  x2*( 0.1*x0*x0 + -0.01*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) )    + x2 * (t > 125.0 ) * ( t < 225.0 ) 
  x3*( -0.1*x1 + -0.2*x1*x2 + 10.0*x0) 
  x2*( 0.2*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( -0.1*x1 + -1.0*x1*x2 + 10.0*x0) 
  x2*( 2.0*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  renaming /library/cell to soma
  Rdesigneur: Elec model has 1 compartments and 0 spines on 1 compartments.
  Chem part of model has  100 dendrite voxels X 7 pools,
      
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0))      
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5)      
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )      
  Traceback (most recent call last):
    File "Fig2_v4.py", line 222, in <module>
      plotPanelCDEF( [0,1,2,3,4], 3 )
    File "Fig2_v4.py", line 171, in plotPanelCDEF
      dt, tplot, avec = runPanelCDEF( 'fhn', 5.0, 0.5, 5, seq, 0.4 )
    File "Fig2_v4.py", line 130, in runPanelCDEF
      Z[k].nInit = 1
  KeyError: 'moose_Id_subscript: invalid index.'
```
- [ ] ./../MemoryNetworks/bidirectional_plastic_switch.py

```
  timeout: the monitored command dumped core
  ebug: User wants Ksolve with 3 threads
```
- [ ] ./../snippets/bidirectionalPlasticity.py

```
  timeout: the monitored command dumped core
  ebug: User wants Ksolve with 3 threads
  Warning: SteadyState iteration failed, status = the iteration has not converged yet, nIter = 100
```
- [ ] ./../snippets/crossComptOscillator.py
- [ ] ./../snippets/crossComptSimpleReac.py

```
  timeout: the monitored command dumped core
  l')
  ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```

```
    timeout: the monitored command dumped core
    l')
    ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
  arning: SteadyState iteration failed, status = input domain error, nIter = 3
```
- [ ] ./../snippets/pyrun.py

```
  Error compiling initString
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/recurrentIntFire.py

```
  Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
  malloc(): memory corruption
  ', 0.0003306865692138672)
  ('after setting connectivity, t = ', 0.010347604751586914)
  ('Middle of setup, t = ', 0.010565757751464844)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.07958531379699707)
  Traceback (most recent call last):
    File "recurrentIntFire.py", line 114, in <module>
      make_network()
    File "recurrentIntFire.py", line 78, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/reacDiffConcGradient.py

```
    Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
    malloc(): memory corruption
    ', 0.0003306865692138672)
    ('after setting connectivity, t = ', 0.010347604751586914)
    ('Middle of setup, t = ', 0.010565757751464844)
    (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
    ('after setup, t = ', 0.07958531379699707)
    Traceback (most recent call last):
      File "recurrentIntFire.py", line 114, in <module>
        make_network()
      File "recurrentIntFire.py", line 78, in make_network
        for j in range( size/numStats ):
    TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdReacDiffusion.py

```
      Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
      malloc(): memory corruption
      ', 0.0003306865692138672)
      ('after setting connectivity, t = ', 0.010347604751586914)
      ('Middle of setup, t = ', 0.010565757751464844)
      (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
      ('after setup, t = ', 0.07958531379699707)
      Traceback (most recent call last):
        File "recurrentIntFire.py", line 114, in <module>
          make_network()
        File "recurrentIntFire.py", line 78, in make_network
          for j in range( size/numStats ):
      TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdFuncDiffusion.py

```
        Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
        malloc(): memory corruption
        ', 0.0003306865692138672)
        ('after setting connectivity, t = ', 0.010347604751586914)
        ('Middle of setup, t = ', 0.010565757751464844)
        (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
        ('after setup, t = ', 0.07958531379699707)
        Traceback (most recent call last):
          File "recurrentIntFire.py", line 114, in <module>
            make_network()
          File "recurrentIntFire.py", line 78, in make_network
            for j in range( size/numStats ):
        TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/recurrentLIF.py

```
  Elements under /network[0]
  /network[0]/syns
  ('before connect t = ', 0.00041031837463378906)
  ('after connect t = ', 0.00043964385986328125)
  ('after setting connectivity, t = ', 0.010904073715209961)
  ('Middle of setup, t = ', 0.011196374893188477)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.07978343963623047)
  Traceback (most recent call last):
    File "recurrentLIF.py", line 120, in <module>
      make_network()
    File "recurrentLIF.py", line 82, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/pyrun1.py

```
    Elements under /network[0]
    /network[0]/syns
    ('before connect t = ', 0.00041031837463378906)
    ('after connect t = ', 0.00043964385986328125)
    ('after setting connectivity, t = ', 0.010904073715209961)
    ('Middle of setup, t = ', 0.011196374893188477)
    (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
    ('after setup, t = ', 0.07978343963623047)
    Traceback (most recent call last):
      File "recurrentLIF.py", line 120, in <module>
        make_network()
      File "recurrentLIF.py", line 82, in make_network
        for j in range( size/numStats ):
    TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../tutorials/ChemicalBistables/doseResponse.py

```
  Debug: User wants Ksolve with 3 threads
  Hit 'enter' to exit
  olve with 3 thr0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=16
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=29
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=10
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=26
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=27
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=30
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=12
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEiscale=0.010	kcat=0.004
  scale=0.013	kcat=0.005
  scale=0.016	kcat=0.006
  scale=0.020	kcat=0.007
  scale=0.025	kcat=0.009
  scale=0.032	kcat=0.011
  scale=0.040	kcat=0.014
  scale=0.050	kcat=0.018
  scale=0.063	kcat=0.023
  scale=0.079	kcat=0.029
  scale=0.100	kcat=0.036
  scale=0.126	kcat=0.045
  scale=0.158	kcat=0.057
  scale=0.200	kcat=0.072
  scale=0.251	kcat=0.091
  scale=0.316	kcat=0.114
  scale=0.398	kcat=0.144
  scale=0.501	kcat=0.181
  scale=0.631	kcat=0.228
  scale=0.794	kcat=0.287
  scale=1.000	kcat=0.361
  scale=1.259	kcat=0.454
  scale=1.585	kcat=0.572
  scale=1.995	kcat=0.720
  scale=2.512	kcat=0.907
  scale=3.162	kcat=1.142
  scale=3.981	kcat=1.437
  scale=5.012	kcat=1.809
  scale=6.310	kcat=2.278
  scale=7.943	kcat=2.868
  scale=10.000	kcat=3.610
  scale=12.589	kcat=4.545
  scale=15.849	kcat=5.722
  scale=19.953	kcat=7.203
  scale=25.119	kcat=9.068
  scale=31.623	kcat=11.416
  scale=39.811	kcat=14.372
  scale=50.119	kcat=18.093
  scale=63.096	kcat=22.778
  scale=79.433	kcat=28.676
  scale=100.000	kcat=36.101
  Traceback (most recent call last):
    File "doseResponse.py", line 126, in <module>
      main()
    File "doseResponse.py", line 112, in main
      pylab.semilogx(joint[0,:],joint[1,:],marker="o",label = 'concA')
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3490, in semilogx
      ret = ax.semilogx(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1724, in semilogx
      self.set_xscale('log', **d)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3183, in set_xscale
      ax.xaxis._set_scale(value, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 772, in _set_scale
      self._scale.set_default_locators_and_formatters(self)
    File "/usr/lib/python3.6/site-packages/matplotlib/scale.py", line 277, in set_default_locators_and_formatters
      axis.set_major_locator(LogLocator(self.base))
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1597, in set_major_locator
      self.stale = True
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 68, in _stale_axes_callback
      self.axes.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 60, in _stale_figure_callback
      self.figure.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 592, in _auto_draw_if_interactive
      fig.canvas.draw_idle()
    File "/usr/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2055, in draw_idle
      self.draw(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
      self.figure.draw(self.renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
      renderer, self, artists, self.suppressComposite)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
      mimage._draw_list_compositing_images(renderer, self, artists)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1190, in draw
      ticks_to_draw = self._update_ticks(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1028, in _update_ticks
      tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 971, in iter_ticks
      majorLocs = self.major.locator()
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2089, in __call__
      return self.tick_values(vmin, vmax)
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2115, in tick_values
      "Data has no positive values, and therefore can not be "
  ValueError: Data has no positive values, and therefore can not be log-scaled.
```
# Following scripts failed 
- [ ] ./../neuroml/LIF/LIFxml_firing.py

```
  moose.nml.neuroml: INFO     Loading neuroml file cells_channels/LIF.morph.xml 
  INFO:moose.nml.neuroml:Loading neuroml file cells_channels/LIF.morph.xml 
  moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
  INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
  INFO:root:Loading cell LIF into /library .
  INFO:root:readMorphML using combineSegments = False
  INFO:root:Loading mechanism IaF into library.
  TypeError: must be real number, not str
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "LIFxml_firing.py", line 47, in <module>
      IF1 = create_LIF()
    File "LIFxml_firing.py", line 32,INFO:root:Loading mechanism Gran_KCa_98 into library.
  _channels/LIF.morph.xml')
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NeuroML.py", line 139, in readNeuroMLFromFile
      cellDict = mmlR.readMorphML(cell,params=params,lengthUnits=self.lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/lobster_pyloric/channels/ChannelTest.py

```
  moose.nml.neuroml: INFO     Loading neuroml file allChannelsCell.net.xml 
  INFO:moose.nml.neuroml:Loading neuroml file allChannelsCell.net.xml 
  moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
  INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
  INFO:root:Reading morphology from /home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism Kd_STG into library.
  INFO:root:Loading mechanism KCa_STG into library.
  L using combineSegments = False
  INFO:root:Loading mechanism Gran_KDr_98 into library.
   direct cause of the following exception:
  
  Traceback (most recent call last):
    File "twoLIFxml_firing.py", line 47, in <module>
      populationDict,projectionDict = create_twoLIFs()
    File "twoLIFxml_firing.py", line 35, in create_twoLIFs
      NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
      return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
      self.network.findall(".//{"+nml_ns+"}population")
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
      [ self.createPopulation(pop) for pop in
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
      cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
      cellDict = self.readMorphML(cell,params,lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/LIF/twoLIFxml_firing.py

```
    moose.nml.neuroml: INFO     Loading neuroml file allChannelsCell.net.xml 
    INFO:moose.nml.neuroml:Loading neuroml file allChannelsCell.net.xml 
    moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
    INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
    INFO:root:Reading morphology from /home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism Kd_STG into library.
    INFO:root:Loading mechanism KCa_STG into library.
    L using combineSegments = False
    INFO:root:Loading mechanism Gran_KDr_98 into library.
     direct cause of the following exception:
    
    Traceback (most recent call last):
      File "twoLIFxml_firing.py", line 47, in <module>
        populationDict,projectionDict = create_twoLIFs()
      File "twoLIFxml_firing.py", line 35, in create_twoLIFs
        NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
        return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
        self.network.findall(".//{"+nml_ns+"}population")
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
        [ self.createPopulation(pop) for pop in
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
        cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
        cellDict = self.readMorphML(cell,params,lengthUnits)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
        moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
    SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../parallelSolver/Fig2_v4.py

```
  tau = 0.004 lambda = 0.00031622776601683794
  0
  -----------------
  4.96729413289805e-10 4.96729413289805e-10 0.0 0.0 0.0 0.0 0.0 0.0 
  0.0 0.0 0.0 0.0 0.0 0.0 4.967Warning: Moogli not found. All moogli calls will use dummy functions
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0)) 
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( 0.1 + -5.0*x1 + 5.0*x1*x1 + -1.0*x1*x1*x1 + 10.0*x0*x1/(1+x1+10*x2) + -5.0*x1*x2) 
  x2*( 0.1*x0*x0 + -0.01*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) )    + x2 * (t > 125.0 ) * ( t < 225.0 ) 
  x3*( -0.1*x1 + -0.2*x1*x2 + 10.0*x0) 
  x2*( 0.2*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( -0.1*x1 + -1.0*x1*x2 + 10.0*x0) 
  x2*( 2.0*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  renaming /library/cell to soma
  Rdesigneur: Elec model has 1 compartments and 0 spines on 1 compartments.
  Chem part of model has  100 dendrite voxels X 7 pools,
      
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0))      
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5)      
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )      
  Traceback (most recent call last):
    File "Fig2_v4.py", line 222, in <module>
      plotPanelCDEF( [0,1,2,3,4], 3 )
    File "Fig2_v4.py", line 171, in plotPanelCDEF
      dt, tplot, avec = runPanelCDEF( 'fhn', 5.0, 0.5, 5, seq, 0.4 )
    File "Fig2_v4.py", line 130, in runPanelCDEF
      Z[k].nInit = 1
  KeyError: 'moose_Id_subscript: invalid index.'
```
- [ ] ./../MemoryNetworks/bidirectional_plastic_switch.py

```
  timeout: the monitored command dumped core
  ebug: User wants Ksolve with 3 threads
```
- [ ] ./../snippets/bidirectionalPlasticity.py

```
  timeout: the monitored command dumped core
  ebug: User wants Ksolve with 3 threads
  Warning: SteadyState iteration failed, status = the iteration has not converged yet, nIter = 100
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
  timeout: the monitored command dumped core
  l')
  ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/crossComptOscillator.py

```
    timeout: the monitored command dumped core
    l')
    ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
  arning: SteadyState iteration failed, status = input domain error, nIter = 3
```
- [ ] ./../snippets/pyrun.py

```
  Error compiling initString
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/recurrentIntFire.py

```
  Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
  malloc(): memory corruption
  , 0.0003306865692138672)
  ('after setting connectivity, t = ', 0.010616779327392578)
  ('Middle of setup, t = ', 0.010855436325073242)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.08195376396179199)
  Traceback (most recent call last):
    File "recurrentIntFire.py", line 114, in <module>
      make_network()
    File "recurrentIntFire.py", line 78, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdFuncDiffusion.py

```
    Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
    malloc(): memory corruption
    , 0.0003306865692138672)
    ('after setting connectivity, t = ', 0.010616779327392578)
    ('Middle of setup, t = ', 0.010855436325073242)
    (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
    ('after setup, t = ', 0.08195376396179199)
    Traceback (most recent call last):
      File "recurrentIntFire.py", line 114, in <module>
        make_network()
      File "recurrentIntFire.py", line 78, in make_network
        for j in range( size/numStats ):
    TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdReacDiffusion.py

```
      Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
      malloc(): memory corruption
      , 0.0003306865692138672)
      ('after setting connectivity, t = ', 0.010616779327392578)
      ('Middle of setup, t = ', 0.010855436325073242)
      (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
      ('after setup, t = ', 0.08195376396179199)
      Traceback (most recent call last):
        File "recurrentIntFire.py", line 114, in <module>
          make_network()
        File "recurrentIntFire.py", line 78, in make_network
          for j in range( size/numStats ):
      TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/reacDiffConcGradient.py

```
        Error: SparseMatrix::setSize( 100000000, 100000000) out of range: ( 200000, 200000)
        malloc(): memory corruption
        , 0.0003306865692138672)
        ('after setting connectivity, t = ', 0.010616779327392578)
        ('Middle of setup, t = ', 0.010855436325073242)
        (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
        ('after setup, t = ', 0.08195376396179199)
        Traceback (most recent call last):
          File "recurrentIntFire.py", line 114, in <module>
            make_network()
          File "recurrentIntFire.py", line 78, in make_network
            for j in range( size/numStats ):
        TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/recurrentLIF.py

```
  Info: Using threaded gsolve: 2 threadsReadKkit::setMethod: option  not known, using Exponential Euler (ee)
   t = ', 0.0004017353057861328)
  ('after setting connectivity, t = ', 0.010494470596313477)
  ('Middle of setup, t = ', 0.010826587677001953)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.07990741729736328)
  Traceback (most recent call last):
    File "recurrentLIF.py", line 120, in <module>
      make_network()
    File "recurrentLIF.py", line 82, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/pyrun1.py

```
    Info: Using threaded gsolve: 2 threadsReadKkit::setMethod: option  not known, using Exponential Euler (ee)
     t = ', 0.0004017353057861328)
    ('after setting connectivity, t = ', 0.010494470596313477)
    ('Middle of setup, t = ', 0.010826587677001953)
    (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
    ('after setup, t = ', 0.07990741729736328)
    Traceback (most recent call last):
      File "recurrentLIF.py", line 120, in <module>
        make_network()
      File "recurrentLIF.py", line 82, in make_network
        for j in range( size/numStats ):
    TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../tutorials/ChemicalBistables/doseResponse.py

```
  Debug: User wants Ksolve with 3 threads
  Hit 'enter' to exit
  olve with 3 thr0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=16
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=29
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=10
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=26
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=27
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=30
  0.18 0.75 0.00 0.03 0.01 Type=0 NeWarning: SteadyState iteration failed, status = input domain error, nIter = 4
  scale=0.010	kcat=0.004
  scale=0.013	kcat=0.005
  scale=0.016	kcat=0.006
  scale=0.020	kcat=0.007
  scale=0.025	kcat=0.009
  scale=0.032	kcat=0.011
  scale=0.040	kcat=0.014
  scale=0.050	kcat=0.018
  scale=0.063	kcat=0.023
  scale=0.079	kcat=0.029
  scale=0.100	kcat=0.036
  scale=0.126	kcat=0.045
  scale=0.158	kcat=0.057
  scale=0.200	kcat=0.072
  scale=0.251	kcat=0.091
  scale=0.316	kcat=0.114
  scale=0.398	kcat=0.144
  scale=0.501	kcat=0.181
  scale=0.631	kcat=0.228
  scale=0.794	kcat=0.287
  scale=1.000	kcat=0.361
  scale=1.259	kcat=0.454
  scale=1.585	kcat=0.572
  scale=1.995	kcat=0.720
  scale=2.512	kcat=0.907
  scale=3.162	kcat=1.142
  scale=3.981	kcat=1.437
  scale=5.012	kcat=1.809
  scale=6.310	kcat=2.278
  scale=7.943	kcat=2.868
  scale=10.000	kcat=3.610
  scale=12.589	kcat=4.545
  scale=15.849	kcat=5.722
  scale=19.953	kcat=7.203
  scale=25.119	kcat=9.068
  scale=31.623	kcat=11.416
  scale=39.811	kcat=14.372
  scale=50.119	kcat=18.093
  scale=63.096	kcat=22.778
  scale=79.433	kcat=28.676
  scale=100.000	kcat=36.101
  Traceback (most recent call last):
    File "doseResponse.py", line 126, in <module>
      main()
    File "doseResponse.py", line 112, in main
      pylab.semilogx(joint[0,:],joint[1,:],marker="o",label = 'concA')
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3490, in semilogx
      ret = ax.semilogx(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1724, in semilogx
      self.set_xscale('log', **d)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3183, in set_xscale
      ax.xaxis._set_scale(value, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 772, in _set_scale
      self._scale.set_default_locators_and_formatters(self)
    File "/usr/lib/python3.6/site-packages/matplotlib/scale.py", line 277, in set_default_locators_and_formatters
      axis.set_major_locator(LogLocator(self.base))
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1597, in set_major_locator
      self.stale = True
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 68, in _stale_axes_callback
      self.axes.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 60, in _stale_figure_callback
      self.figure.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 592, in _auto_draw_if_interactive
      fig.canvas.draw_idle()
    File "/usr/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2055, in draw_idle
      self.draw(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
      self.figure.draw(self.renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
      renderer, self, artists, self.suppressComposite)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
      mimage._draw_list_compositing_images(renderer, self, artists)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1190, in draw
      ticks_to_draw = self._update_ticks(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1028, in _update_ticks
      tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 971, in iter_ticks
      majorLocs = self.major.locator()
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2089, in __call__
      return self.tick_values(vmin, vmax)
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2115, in tick_values
      "Data has no positive values, and therefore can not be "
  ValueError: Data has no positive values, and therefore can not be log-scaled.
```
# Following scripts failed 
- [ ] ./../neuroml/LIF/LIFxml_firing.py

```
  moose.nml.neuroml: INFO     Loading neuroml file cells_channels/LIF.morph.xml 
  INFO:moose.nml.neuroml:Loading neuroml file cells_channels/LIF.morph.xml 
  moose.nml.neuroml: INFO     Using default temperature of 32.0 degree Celsius
  INFO:moose.nml.neuroml:Using default temperature of 32.0 degree Celsius
  INFO:root:Loading cell LIF into /library .
  INFO:root:readMorphML using combineSegments = False
  INFO:root:Loading mechanism IaF into library.
  TypeError: must be real number, not str
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last)INFO:root:Loading mechanism Gran_H_98 into library.
  INFO:root:Loading mechanism Gran_CaHVA_98 into library.
  INFO:root:Loading mechanism Gran_KCa_98 into library.
  _channels/LIF.morph.xml')
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NeuroML.py", line 139, in readNeuroMLFromFile
      cellDict = mmlR.readMorphML(cell,params=params,lengthUnits=self.lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/LIF/twoLIFxml_firing.py

```
  Selecting a channel randomly form ['H_STG', 'CaS_STG', 'CaT_STG', 'KA_STG', 'Kd_STG', 'Na_STG']
  Selected CaS_STG
  Traceback (most recent call last):
    File "ChannelTest.py", line 41, in <module>
      for varidx in range(len(mechanism_vars)/2): # loop over each inf and tau
  TypeError: 'float' object cannot be interpreted as an integer
  dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism KINFO:root:Loading ceINFO:root:Loading mechanism KCa_STG into library.
  L using combineSegments = False
  INFO:root:Loading mechanism Gran_KDr_98 into library.
   direct cause of the following exception:
  
  Traceback (most recent call last):
    File "twoLIFxml_firing.py", line 47, in <module>
      populationDict,projectionDict = create_twoLIFs()
    File "twoLIFxml_firing.py", line 35, in create_twoLIFs
      NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
      return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
      self.network.findall(".//{"+nml_ns+"}population")
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
      [ self.createPopulation(pop) for pop in
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
      cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
      cellDict = self.readMorphML(cell,params,lengthUnits)
    File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
      moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
  SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../neuroml/lobster_pyloric/channels/ChannelTest.py

```
    Selecting a channel randomly form ['H_STG', 'CaS_STG', 'CaT_STG', 'KA_STG', 'Kd_STG', 'Na_STG']
    Selected CaS_STG
    Traceback (most recent call last):
      File "ChannelTest.py", line 41, in <module>
        for varidx in range(len(mechanism_vars)/2): # loop over each inf and tau
    TypeError: 'float' object cannot be interpreted as an integer
    dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/neuroml/allChannelsCell/cells_cINFO:root:Loading mechanism KINFO:root:Loading ceINFO:root:Loading mechanism KCa_STG into library.
    L using combineSegments = False
    INFO:root:Loading mechanism Gran_KDr_98 into library.
     direct cause of the following exception:
    
    Traceback (most recent call last):
      File "twoLIFxml_firing.py", line 47, in <module>
        populationDict,projectionDict = create_twoLIFs()
      File "twoLIFxml_firing.py", line 35, in create_twoLIFs
        NML.readNetworkMLFromFile('twoLIFs.net.xml', {}, params={})
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 76, in readNetworkMLFromFile
        return self.readNetworkML(root_element,cellSegmentDict,params,root_element.attrib['lengthUnits'])
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 93, in readNetworkML
        self.network.findall(".//{"+nml_ns+"}population")
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 92, in <listcomp>
        [ self.createPopulation(pop) for pop in
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/NetworkML.py", line 184, in createPopulation
        cellDict = mmlR.readMorphMLFromFile(model_path, self.params)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 79, in readMorphMLFromFile
        cellDict = self.readMorphML(cell,params,lengthUnits)
      File "/home1/dilawars/Work/GITHUB/DILAWAR/moose-core/_build/python/moose/neuroml/MorphML.py", line 267, in readMorphML
        moosechannelval = moose.Mstring(moosechannel.path+'/thresh')
    SystemError: <class 'moose.moose.Mstring'> returned a result with an error set
```
- [ ] ./../parallelSolver/Fig2_v4.py

```
  tau = 0.004 lambda = 0.00031622776601683794
  0
  -----------------
  4.96729413289805e-10 4.96729413289805e-10 0.0 0.0 0.0 0.0 0.0 0.0 
  0.0 0.0 0.0 0.0 0.0 0.0 4.967Warning: Moogli not found. All moogli calls will use dummy functions
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0)) 
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( 0.1 + -5.0*x1 + 5.0*x1*x1 + -1.0*x1*x1*x1 + 10.0*x0*x1/(1+x1+10*x2) + -5.0*x1*x2) 
  x2*( 0.1*x0*x0 + -0.01*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 25.0) )    + x2 * (t > 125.0 ) * ( t < 225.0 ) 
  x3*( -0.1*x1 + -0.2*x1*x2 + 10.0*x0) 
  x2*( 0.2*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  x3*( -0.1*x1 + -1.0*x1*x2 + 10.0*x0) 
  x2*( 2.0*x0 + -0.1*x1) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) ) 
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )    + x2 * (t > 71.0 ) * ( t < 171.0 ) 
  renaming /library/cell to soma
  Rdesigneur: Elec model has 1 compartments and 0 spines on 1 compartments.
  Chem part of model has  100 dendrite voxels X 7 pools,
      
  x3*( 5.0*(x1 - 2.0 - (x1-2.0)^3/3 - (x2-0.8) + x0))      
  x2*( (x0-2.0 + 0.7 - 0.8*(x1-0.8))/2.5)      
  x2 * exp( -((x0 - t)^2)/(2* 1.0) )      
  Traceback (most recent call last):
    File "Fig2_v4.py", line 222, in <module>
      plotPanelCDEF( [0,1,2,3,4], 3 )
    File "Fig2_v4.py", line 171, in plotPanelCDEF
      dt, tplot, avec = runPanelCDEF( 'fhn', 5.0, 0.5, 5, seq, 0.4 )
    File "Fig2_v4.py", line 130, in runPanelCDEF
      Z[k].nInit = 1
  KeyError: 'moose_Id_subscript: invalid index.'
```
- [ ] ./../traub_2005/py/fig_a2_fs.py

```
  Traceback (most recent call last):
    File "fig_a3.py", line 55, in <module>
      from cells import SpinyStellate
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/fig_a3.py

```
    Traceback (most recent call last):
      File "fig_a3.py", line 55, in <module>
        from cells import SpinyStellate
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/dump_f_i_curves.py

```
      Traceback (most recent call last):
        File "fig_a3.py", line 55, in <module>
          from cells import SpinyStellate
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/display_morphology.py

```
        Traceback (most recent call last):
          File "fig_a3.py", line 55, in <module>
            from cells import SpinyStellate
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_capool.py

```
  Traceback (most recent call last):
    File "fig_a4c.py", line 56, in <module>
      from cells import TuftedIB
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/fig_a4c.py

```
    Traceback (most recent call last):
      File "fig_a4c.py", line 56, in <module>
        from cells import TuftedIB
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_archan.py

```
      Traceback (most recent call last):
        File "fig_a4c.py", line 56, in <module>
          from cells import TuftedIB
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_cachans.py

```
        Traceback (most recent call last):
          File "fig_a4c.py", line 56, in <module>
            from cells import TuftedIB
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cells.py", line 36, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_deepbasket.py

```
  Traceback (most recent call last):
    File "test_deepbasket.py", line 33, in <module>
      from cell_test_util import SingleCellCurrentStepTest
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_deepaxoaxonic.py

```
    Traceback (most recent call last):
      File "test_deepbasket.py", line 33, in <module>
        from cell_test_util import SingleCellCurrentStepTest
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_hsolve_tcr.py
- [ ] ./../traub_2005/py/test_deeplts.py

```
      Traceback (most recent call last):
        File "test_deepbasket.py", line 33, in <module>
          from cell_test_util import SingleCellCurrentStepTest
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
```

```
        Traceback (most recent call last):
          File "test_deepbasket.py", line 33, in <module>
            from cell_test_util import SingleCellCurrentStepTest
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_nrt.py

```
  Traceback (most recent call last):
    File "test_nachans.py", line 38, in <module>
      import testutils
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/testutils.py", line 44, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
  eNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_kchans.py

```
    Traceback (most recent call last):
      File "test_nachans.py", line 38, in <module>
        import testutils
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/testutils.py", line 44, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
    eNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_nontuftedrs.py

```
      Traceback (most recent call last):
        File "test_nachans.py", line 38, in <module>
          import testutils
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/testutils.py", line 44, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
      eNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_nachans.py

```
        Traceback (most recent call last):
          File "test_nachans.py", line 38, in <module>
            import testutils
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/testutils.py", line 44, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
        eNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_supbasket.py

```
  Traceback (most recent call last):
    File "test_spinystellate.py", line 33, in <module>
      from cell_test_util import SingleCellCurrentStepTest
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_supaxoaxonic.py

```
    Traceback (most recent call last):
      File "test_spinystellate.py", line 33, in <module>
        from cell_test_util import SingleCellCurrentStepTest
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_spinystellate.py

```
      Traceback (most recent call last):
        File "test_spinystellate.py", line 33, in <module>
          from cell_test_util import SingleCellCurrentStepTest
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_singlecomp.py

```
        Traceback (most recent call last):
          File "test_spinystellate.py", line 33, in <module>
            from cell_test_util import SingleCellCurrentStepTest
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_suppyrfrb.py

```
  Traceback (most recent call last):
    File "test_suppyrrs.py", line 33, in <module>
      from cell_test_util import SingleCellCurrentStepTest
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
  e named 'exceptions'
```
- [ ] ./../traub_2005/py/test_tcr.py

```
    Traceback (most recent call last):
      File "test_suppyrrs.py", line 33, in <module>
        from cell_test_util import SingleCellCurrentStepTest
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
    e named 'exceptions'
```
- [ ] ./../traub_2005/py/test_suppyrrs.py

```
      Traceback (most recent call last):
        File "test_suppyrrs.py", line 33, in <module>
          from cell_test_util import SingleCellCurrentStepTest
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
          import config
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
          import settings
        File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
          import exceptions
      ModuleNotFoundError: No module named 'exceptions'
      e named 'exceptions'
```
- [ ] ./../traub_2005/py/test_suplts.py

```
        Traceback (most recent call last):
          File "test_suppyrrs.py", line 33, in <module>
            from cell_test_util import SingleCellCurrentStepTest
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
            import config
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
            import settings
          File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
            import exceptions
        ModuleNotFoundError: No module named 'exceptions'
        e named 'exceptions'
```
- [ ] ./../traub_2005/py/test_tuftedrs.py

```
  Traceback (most recent call last):
    File "test_tuftedib.py", line 33, in <module>
      from cell_test_util import SingleCellCurrentStepTest
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
      import config
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
      import settings
    File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
      import exceptions
  ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../traub_2005/py/test_tuftedib.py

```
    Traceback (most recent call last):
      File "test_tuftedib.py", line 33, in <module>
        from cell_test_util import SingleCellCurrentStepTest
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/cell_test_util.py", line 46, in <module>
        import config
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/config.py", line 33, in <module>
        import settings
      File "/home1/dilawars/Work.SVN/GITHUB/BhallaLab/moose-examples/traub_2005/py/settings.py", line 31, in <module>
        import exceptions
    ModuleNotFoundError: No module named 'exceptions'
```
- [ ] ./../MemoryNetworks/bidirectional_plastic_switch.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/bidirectionalPlasticity.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  timeout: the monitored command dumped core
  l')
  ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/crossComptSimpleReac.py

```
    timeout: the monitored command dumped core
    l')
    ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/crossComptOscillator.py

```
      timeout: the monitored command dumped core
      l')
      ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
```
- [ ] ./../snippets/reacDiffConcGradient.py

```
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/pyrun.py

```
    timeout: the monitored command dumped core
```
- [ ] ./../snippets/recurrentIntFire.py

```
  Elements under /network[0]
  /network[0]/syns
  ('before connect t = ', 0.0003497600555419922)
  ('after connect t = ', 0.0003800392150878906)
  ('after setting connectivity, t = ', 0.010437488555908203)
  ('Middle of setup, t = ', 0.010679960250854492)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.07775402069091797)
  Traceback (most recent call last):
    File "recurrentIntFire.py", line 114, in <module>
      make_network()
    File "recurrentIntFire.py", line 78, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdReacDiffusion.py

```
    Elements under /network[0]
    /network[0]/syns
    ('before connect t = ', 0.0003497600555419922)
    ('after connect t = ', 0.0003800392150878906)
    ('after setting connectivity, t = ', 0.010437488555908203)
    ('Middle of setup, t = ', 0.010679960250854492)
    (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
    ('after setup, t = ', 0.07775402069091797)
    Traceback (most recent call last):
      File "recurrentIntFire.py", line 114, in <module>
        make_network()
      File "recurrentIntFire.py", line 78, in make_network
        for j in range( size/numStats ):
    TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/rxdFuncDiffusion.py

```
      Elements under /network[0]
      /network[0]/syns
      ('before connect t = ', 0.0003497600555419922)
      ('after connect t = ', 0.0003800392150878906)
      ('after setting connectivity, t = ', 0.010437488555908203)
      ('Middle of setup, t = ', 0.010679960250854492)
      (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
      ('after setup, t = ', 0.07775402069091797)
      Traceback (most recent call last):
        File "recurrentIntFire.py", line 114, in <module>
          make_network()
        File "recurrentIntFire.py", line 78, in make_network
          for j in range( size/numStats ):
      TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../snippets/pyrun1.py

```
  Error compiling initString
  timeout: the monitored command dumped core
```
- [ ] ./../snippets/recurrentLIF.py

```
  Written to file testsave.g
  ('', True)
  /syns
  ('before connect t = ', 0.00040030479431152344)
  ('after connect t = ', 0.0004298686981201172)
  ('after setting connectivity, t = ', 0.01163792610168457)
  ('Middle of setup, t = ', 0.01200103759765625)
  (1024, ', tot = ', 10536, ', numSynVec = ', array([10,  7, 13, ..., 15,  9,  5], dtype=uint32))
  ('after setup, t = ', 0.08085894584655762)
  Traceback (most recent call last):
    File "recurrentLIF.py", line 120, in <module>
      make_network()
    File "recurrentLIF.py", line 82, in make_network
      for j in range( size/numStats ):
  TypeError: 'float' object cannot be interpreted as an integer
```
- [ ] ./../tutorials/ChemicalBistables/doseResponse.py

```
  Debug: User wants Ksolve with 3 threads
  
  
  Totals:	-3273.39	3377.49	
  gamma[20.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=16
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=29
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=10
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=26
  0.18 0.75 0.00 0.03 0.01 Type=0 NegEig=3 PosEig=0 status=0 success Iter=27
  0.92 0.05 0.00 0.01 0.01 Type=2 NegEig=2 PosEig=1 status=0 success Iter=30
  0.18 0.75 0.00 0.03 0.01 Type=0 NeWarning: SteadyState iteration failed, status = input domain error, nIter = 4
  scale=0.010	kcat=0.004
  scale=0.013	kcat=0.005
  scale=0.016	kcat=0.006
  scale=0.020	kcat=0.007
  scale=0.025	kcat=0.009
  scale=0.032	kcat=0.011
  scale=0.040	kcat=0.014
  scale=0.050	kcat=0.018
  scale=0.063	kcat=0.023
  scale=0.079	kcat=0.029
  scale=0.100	kcat=0.036
  scale=0.126	kcat=0.045
  scale=0.158	kcat=0.057
  scale=0.200	kcat=0.072
  scale=0.251	kcat=0.091
  scale=0.316	kcat=0.114
  scale=0.398	kcat=0.144
  scale=0.501	kcat=0.181
  scale=0.631	kcat=0.228
  scale=0.794	kcat=0.287
  scale=1.000	kcat=0.361
  scale=1.259	kcat=0.454
  scale=1.585	kcat=0.572
  scale=1.995	kcat=0.720
  scale=2.512	kcat=0.907
  scale=3.162	kcat=1.142
  scale=3.981	kcat=1.437
  scale=5.012	kcat=1.809
  scale=6.310	kcat=2.278
  scale=7.943	kcat=2.868
  scale=10.000	kcat=3.610
  scale=12.589	kcat=4.545
  scale=15.849	kcat=5.722
  scale=19.953	kcat=7.203
  scale=25.119	kcat=9.068
  scale=31.623	kcat=11.416
  scale=39.811	kcat=14.372
  scale=50.119	kcat=18.093
  scale=63.096	kcat=22.778
  scale=79.433	kcat=28.676
  scale=100.000	kcat=36.101
  Traceback (most recent call last):
    File "doseResponse.py", line 126, in <module>
      main()
    File "doseResponse.py", line 112, in main
      pylab.semilogx(joint[0,:],joint[1,:],marker="o",label = 'concA')
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3490, in semilogx
      ret = ax.semilogx(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1724, in semilogx
      self.set_xscale('log', **d)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3183, in set_xscale
      ax.xaxis._set_scale(value, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 772, in _set_scale
      self._scale.set_default_locators_and_formatters(self)
    File "/usr/lib/python3.6/site-packages/matplotlib/scale.py", line 277, in set_default_locators_and_formatters
      axis.set_major_locator(LogLocator(self.base))
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1597, in set_major_locator
      self.stale = True
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 68, in _stale_axes_callback
      self.axes.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 60, in _stale_figure_callback
      self.figure.stale = val
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
      self.stale_callback(self, val)
    File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 592, in _auto_draw_if_interactive
      fig.canvas.draw_idle()
    File "/usr/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2055, in draw_idle
      self.draw(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
      self.figure.draw(self.renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
      renderer, self, artists, self.suppressComposite)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
      mimage._draw_list_compositing_images(renderer, self, artists)
    File "/usr/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
      a.draw(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
      return draw(artist, renderer, *args, **kwargs)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1190, in draw
      ticks_to_draw = self._update_ticks(renderer)
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 1028, in _update_ticks
      tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
    File "/usr/lib/python3.6/site-packages/matplotlib/axis.py", line 971, in iter_ticks
      majorLocs = self.major.locator()
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2089, in __call__
      return self.tick_values(vmin, vmax)
    File "/usr/lib/python3.6/site-packages/matplotlib/ticker.py", line 2115, in tick_values
      "Data has no positive values, and therefore can not be "
  ValueError: Data has no positive values, and therefore can not be log-scaled.
```
# Following scripts failed 
- [ ] ./../snippets/crossComptSimpleReac.py

```
  ('Ticks connected to `process` method of', '/comp[0]')
  (' ->', '/clock')
  ('Ticks connected to `init` method of', '/comp[0]')
  (' ->', '/clock')
  Elements on tick 0
  (' ->', '/comp')
  Elements on tick 1
  (' ->', '/comp')
  ('/comp[0]/chan[0]', 'has been scheduled')
  Elements on tick 1
  (' ->', '/comp')
  (' ->', '/comp[0]/chan')
  ('Ticks connected to `process` method of', '/comp[0]')
  (' ->', '/clock')
```
- [ ] ./../snippets/crossComptSimpleReacGSSA.py

```
  Hello: current time: 2018-07-20T20:34:44.464838
  World: current time: 2018-07-20T20:34:44.465059
  Init <moose.PyRun: id=453, dataIndex=0, path=/model[0]/Hello[0]>
  Running Hello
  Hello count = 0
  Init World
  Running World
  World count = 0
  Running Hello
  Hello count = 1
  Running World
  World count = 1
  Running Hello
  Hello count = 2
  Running World
  World count = 2
  Running Hello
  Hello count = 3
  Running World
  World count = 3
  Running Hello
  Hello count = 4
  Running World
  World count = 4
  Running Hello
  Hello count = 5
  Running World
  World count = 5
  Running Hello
  Hello count = 6
  Running World
  World count = 6
  Running Hello
  Hello count = 7
  Running World
  World count = 7
  Running Hello
  Hello count = 8
  Running World
  World count = 8
  Running Hello
  Hello count = 9
  Running World
  World count = 9
  Running Hello
  Hello count = 10
  Running World
  World count = 10
  Running Hello
  Hello count = 11
  Running World
  World count = 11
  Running Hello
  Hello count = 12
  Running World
  World count = 12
  Running Hello
  Hello count = 13
  Running World
  World count = 13
  Running Hello
  Hello count = 14
  Running World
  World count = 14
  Running Hello
  Hello count = 15
  Running World
  World count = 15
  Running Hello
  Hello count = 16
  Running World
  World count = 16
  Running Hello
  Hello count = 17
  Running World
  World count = 17
  Running Hello
  Hello count = 18
  Running World
  World count = 18
  Running Hello
  Hello count = 19
  Running World
  World count = 19
  Running Hello
  Hello count = 20
  Running World
  World count = 20
  Init World
  Running World
  World count = 0
  input = 0.0
  output = 0.0
  Running World
  World count = 1
  input = 0.0
  output = 0.0
  Running World
  World count = 2
  input = 0.0
  output = 0.0
  Running World
  World count = 3
  input = 0.0
  output = 0.0
  Running World
  World count = 4
  input = 1.0
  output = 1.0
  Running World
  World count = 5
  input = 1.0
  output = 1.0
  Running World
  World count = 6
  input = 1.0
  output = 1.0
  Running World
  World count = 7
  input = 1.0
  output = 1.0
  Running World
  World count = 8
  input = 2.0
  output = 4.0
  Running World
  World count = 9
  input = 2.0
  output = 4.0
  Running World
  World count = 10
  input = 2.0
  output = 4.0
  Running World
  World count = 11
  input = 2.0
  output = 4.0
  Running World
  World count = 12
  input = 3.0
  output = 9.0
  Running World
  World count = 13
  input = 3.0
  output = 9.0
  Running World
  World count = 14
  input = 3.0
  output = 9.0
  Running World
  World count = 15
  input = 3.0
  output = 9.0
  Running World
  World count = 16
  input = 0.0
  output = 0.0
  Running World
  World count = 17
  input = 0.0
  output = 0.0
  Running World
  World count = 18
  input = 0.0
  output = 0.0
  Running World
  World count = 19
  input = 0.0
  output = 0.0
  Running World
  World count = 20
  input = 1.0
  output = 1.0
  Running World
  World count = 21
  input = 1.0
  output = 1.0
  Running World
  World count = 22
  input = 1.0
  output = 1.0
  Running World
  World count = 23
  input = 1.0
  output = 1.0
  Running World
  World count = 24
  input = 2.0
  output = 4.0
  Running World
  World count = 25
  input = 2.0
  output = 4.0
  Running World
  World count = 26
  input = 2.0
  output = 4.0
  Running World
  World count = 27
  input = 2.0
  output = 4.0
  Running World
  World count = 28
  input = 3.0
  output = 9.0
  Running World
  World count = 29
  input = 3.0
  output = 9.0
  Running World
  World count = 30
  input = 3.0
  output = 9.0
  Running World
  World count = 31
  input = 3.0
  output = 9.0
  Running World
  World count = 32
  input = 0.0
  output = 0.0
  Running World
  World count = 33
  input = 0.0
  output = 0.0
  Running World
  World count = 34
  input = 0.0
  output = 0.0
  Running World
  World count = 35
  input = 0.0
  output = 0.0
  Running World
  World count = 36
  input = 1.0
  output = 1.0
  Running World
  World count = 37
  input = 1.0
  output = 1.0
  Running World
  World count = 38
  input = 1.0
  output = 1.0
  Running World
  World count = 39
  input = 1.0
  output = 1.0
  Running World
  World count = 40
  input = 2.0
  output = 4.0
```
- [ ] ./../snippets/loadSbmlmodel.py

```
  [FATAL] Module python-libsbml is not found.
  This module can be installed by following command in terminal:
  	 easy_install python-libsbml
  Traceback (most recent call last):
    File "loadSbmlmodel.py", line 122, in <module>
      modelPath, modelpathexist,msg = main()
    File "loadSbmlmodel.py", line 84, in main
      elif sbmlId.path != '/':
  AttributeError: 'NoneType' object has no attribute 'path'
```
- [ ] ./../snippets/reacDiffConcGradient.py

```
```
- [ ] ./../snippets/hdfdemo.py

```
  Traceback (most recent call last):
    File "hdfdemo.py", line 102, in <module>
      main()
    File "hdfdemo.py", line 99, in main
      example()
    File "hdfdemo.py", line 18, in example
      hdfwriter = moose.HDF5DataWriter('h')
  AttributeError: 'module' object has no attribute 'HDF5DataWriter'
```
- [ ] ./../snippets/nsdf.py

```
  Traceback (most recent call last):
    File "nsdf.py", line 173, in <module>
      main()
    File "nsdf.py", line 170, in main
      setup_model()
    File "nsdf.py", line 123, in setup_model
      nsdf = moose.NSDFWriter('/model/writer')
  AttributeError: 'module' object has no attribute 'NSDFWriter'
```
- [ ] ./../traub_2005/py/dump_f_i_curves.py

```
  Traceback (most recent call last):
    File "dump_f_i_curves.py", line 51, in <module>
      import h5py as h5
  ImportError: No module named h5py
```
